name: GetDown
version: '1.0-SNAPSHOT'
main: tv.logisch.game.GetDown
api-version: '1.21'
authors: [Teekqu]
description: Minigame for Logisch.tv
website: https://www.teekqu.de/

commands:
  start:
    description: Start the GetDown minigame
  coins:
    description: Manage the coins of a player
  skip:
    description: Skip the shopping phase
